Test2022/Controllers/ValidateparenthesesTask4Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Test2022.Controllers
{
    public class ValidateparenthesesTask4Controller : Controller
    {
        // GET: ValidateparenthesesTask4
        public ActionResult ValidateparenthesesTask4View()
        {
            return View();
        }
        public ActionResult ValidateInput(string LISPCode)
        {
            int Num = CheckInputFile(LISPCode);

            if (Num == 0) return Json("Failed", JsonRequestBehavior.AllowGet);
            else return Json("Success", JsonRequestBehavior.AllowGet);

        }

        public int CheckInputFile(string LISPCode)
        {

            // Return 1 if string size is 0 
            if (LISPCode.Length == 0) return 1;

            Stack<char> brackets = new Stack<char>();

            foreach (char c in LISPCode)
            {
                if (c == '[' || c == '{' || c == '(')
                {
                    brackets.Push(c);
                }
                else
                {                    
                        if (c == ')')
                        {
                            if (brackets.Count > 0) // check if the stack count is greater then 0
                            {
                                if (brackets.Peek() == '(') brackets.Pop();
                                else return 0;
                            }
                             else return 0;
                        }

                        if (c == '}')
                        {
                            if (brackets.Count > 0) // check if the stack count is greater then 0
                            {
                                if (brackets.Peek() == '{') brackets.Pop();
                                else return 0;
                            }

                            else return 0;
                        }

                        if (c == ']')
                        {
                                if (brackets.Count > 0) // check if the stack count is greater then 0
                                {
                                    if (brackets.Peek() == '[') brackets.Pop();
                                else return 0;
                            }
                            else return 0;
                        }
                   

                }
            }

            // if there are no parantheses in the stack then it is valid string
            if (brackets.Count == 0) return 1;

            return 0;
        }
    }
}

Test2022/Views/ValidateparenthesesTask4/ValidateparenthesesTask4View.cshtml
@{
    ViewBag.Title = "Validate parentheses";
}

<h2>Validate LISP Code</h2>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<!--Kendo CSS-->
@Styles.Render("~/Content/kendo-css")

<!--Kendo JS-->
@Scripts.Render("~/bundles/jquery")
@*@Scripts.Render("~/bundles/jqueryui")*@
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/kendo")
@Scripts.Render("~/bundles/app")
<script>

$(document).ready(function () {
//***************************************************************************************************************************************************************************************************************************
    $("#btnValidate").click(function () {

        var LISPCode = document.getElementsByName('LISPCode')[0].value;
        if (LISPCode != '') {


            $.ajax({
                type: "POST",
                url: "@Url.Action("ValidateInput", "ValidateparenthesesTask4")",

                data: { LISPCode: LISPCode },

                success: function (data) {
                    if (data == "Success") {
                        alert('Input string has the balanced parentheses.');
                    }
                    else if (data == "Failed") {
                        alert('String is invalid! Input string has not the balanced parentheses.');
                    }

                }

            })

        }
        else {
            alert('Please enter the valid input.');
        }
        });

//***************************************************************************************************************************************************************************************************************************
});
</script>

<div>

    @Html.TextArea("LISPCode", new { @style = "color:black", cols = "20", rows = "20" })<br />
    <input type="button" class="btn btn-primary ks-rounded" id="btnValidate" value="Validate" />&nbsp;
</div>